#!/usr/bin/env bash
# Prepares the iOS project with credentials that must never be committed.
# Run on the Mac / CI before `flutter build ios` or `flutter build ipa`.
#
# Inputs (environment variables — set them as CI secrets, never in git):
#   GOOGLE_SERVICE_INFO_PLIST_B64  base64 of GoogleService-Info.plist   (or place the file at ios/Runner/)
#   GMS_API_KEY_IOS                Google Maps SDK for iOS key
set -euo pipefail
cd "$(dirname "$0")/.."
PLIST=ios/Runner/GoogleService-Info.plist

if [[ -n "${GOOGLE_SERVICE_INFO_PLIST_B64:-}" ]]; then
  echo "$GOOGLE_SERVICE_INFO_PLIST_B64" | base64 --decode > "$PLIST"
fi
if [[ ! -f "$PLIST" ]]; then
  if [[ "${REQUIRE_REAL_FIREBASE:-0}" == "1" ]]; then
    echo "✗ $PLIST missing and REQUIRE_REAL_FIREBASE=1 — refusing to build a release that cannot reach Firebase."
    exit 1
  fi
  echo "⚠ $PLIST missing — writing a placeholder so the compile check can run. This build cannot reach Firebase."
  cat > "$PLIST" <<'PL'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>API_KEY</key><string>placeholder</string>
  <key>GCM_SENDER_ID</key><string>000000000000</string>
  <key>PLIST_VERSION</key><string>1</string>
  <key>BUNDLE_ID</key><string>com.surpl.app</string>
  <key>PROJECT_ID</key><string>placeholder</string>
  <key>STORAGE_BUCKET</key><string>placeholder.appspot.com</string>
  <key>GOOGLE_APP_ID</key><string>1:000000000000:ios:0000000000000000</string>
</dict></plist>
PL
  REV="com.googleusercontent.apps.placeholder"; ENC="app-placeholder"
else
  read_key() { /usr/libexec/PlistBuddy -c "Print :$1" "$PLIST" 2>/dev/null || python3 -c "import plistlib,sys;print(plistlib.load(open('$PLIST','rb')).get('$1',''))"; }
  GOOGLE_APP_ID="$(read_key GOOGLE_APP_ID)"
  REV="$(read_key REVERSED_CLIENT_ID || true)"
  ENC="app-${GOOGLE_APP_ID//:/-}"
  if [[ -z "$REV" ]]; then
    echo "ℹ No REVERSED_CLIENT_ID in GoogleService-Info.plist: Google Sign-In stays off on iOS (phone sign-in is unaffected)."
    REV="com.googleusercontent.apps.not-configured"
  fi
fi
[[ -n "${GMS_API_KEY_IOS:-}" ]] || echo "⚠ GMS_API_KEY_IOS not set — map tiles will be blank."

cat > ios/Flutter/Secrets.xcconfig <<XC
// GENERATED by scripts/ios-setup.sh — do not commit.
GMS_API_KEY = ${GMS_API_KEY_IOS:-}
GOOGLE_REVERSED_CLIENT_ID = ${REV}
FIREBASE_ENCODED_APP_ID = ${ENC}
XC
echo "✓ iOS secrets prepared (values not printed)."
