#!/usr/bin/env bash
# Prepares the iOS project with credentials that must never be committed.
# Run on the Mac / CI before `flutter build ios` or `flutter build ipa`.
#
# Inputs (environment variables — set them as CI secrets, never in git):
#   GOOGLE_SERVICE_INFO_PLIST_B64  base64 of GoogleService-Info.plist   (or place the file at ios/Runner/)
#   GMS_API_KEY_IOS                Google Maps SDK for iOS key
set -euo pipefail
cd "$(dirname "$0")/.."
PLIST=ios/Runner/GoogleService-Info.plist

if [[ -n "${GOOGLE_SERVICE_INFO_PLIST_B64:-}" ]]; then
  echo "$GOOGLE_SERVICE_INFO_PLIST_B64" | base64 --decode > "$PLIST"
fi
if [[ ! -f "$PLIST" ]]; then
  echo "⚠ $PLIST missing — building with placeholders (compiles, but Firebase won't connect)."
  REV="com.googleusercontent.apps.placeholder"; ENC="app-placeholder"
else
  read_key() { /usr/libexec/PlistBuddy -c "Print :$1" "$PLIST" 2>/dev/null || python3 -c "import plistlib,sys;print(plistlib.load(open('$PLIST','rb')).get('$1',''))"; }
  GOOGLE_APP_ID="$(read_key GOOGLE_APP_ID)"
  REV="$(read_key REVERSED_CLIENT_ID || true)"
  ENC="app-${GOOGLE_APP_ID//:/-}"
  if [[ -z "$REV" ]]; then
    echo "ℹ No REVERSED_CLIENT_ID in GoogleService-Info.plist: Google Sign-In stays off on iOS (phone sign-in is unaffected)."
    REV="com.googleusercontent.apps.not-configured"
  fi
fi
[[ -n "${GMS_API_KEY_IOS:-}" ]] || echo "⚠ GMS_API_KEY_IOS not set — map tiles will be blank."

cat > ios/Flutter/Secrets.xcconfig <<XC
// GENERATED by scripts/ios-setup.sh — do not commit.
GMS_API_KEY = ${GMS_API_KEY_IOS:-}
GOOGLE_REVERSED_CLIENT_ID = ${REV}
FIREBASE_ENCODED_APP_ID = ${ENC}
XC
echo "✓ iOS secrets prepared (values not printed)."
